AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
Style/HashSyntax:
  Exclude:
    - '**/subscription.rb'
Rails:
  Enabled: true
Documentation:
  Enabled: false
