AllCops:
  TargetRubyVersion: 2.4.1
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
Style/HashSyntax:
  Exclude:
    - '**/subscription.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Rails:
  Enabled: true
Documentation:
  Enabled: false
