require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - '.gems/**/*'
    - 'vendor/**/*'
Style/HashSyntax:
  Exclude:
    - '**/subscription.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Rails:
  Enabled: true
Documentation:
  Enabled: false
