AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
Metrics/LineLength:
  Exclude:
    - '**/GemFile'
Rails:
  Enabled: true
Documentation:
  Enabled: false
